defaults:
  - base_io

tournaments_gdrive: https://docs.google.com/spreadsheets/d/e/2PACX-1vRGtdIhhS1sVzLL07lnYHO05wwmo-J7E8gRRjQbM6EOr3YA-d0xYKXne5LjZDuVXx_NpDREZCYNM34H/pub?output=xlsx
tournaments_spreadsheet_id: 16HAz4rQ_llavYjobJicD5mhJg1m16E2uRBkv7Jdc9aQ
temporal_spreadsheet_id: 1qM8DxABfcCCU5_LZjg1794JJUBgqX7XXSH25XZieeLA
published_on_web_spreadsheets_id:
  - 1niDg_mLqoFOCSnkykiYppWImP4Ef_tZcrJwjgeYJKA4  # partidos
  - 1TE8JayF7Q8SCUd4G10B8Y_1_lV_4tzvLzTN1zRifMEg  # nivel de juego
  - 1FMygcBXuHxMsL-zPutgKKj-hGlhTDZmnpwcc2ehiezA  # detalles nivel de juego
  - 1Pu3ciRKIN4p3tPD4kDhXYn1Z8hRQNzBLiCjFivyubjQ  # campeonato primera
  - 1YVjg2iP6TXdJS26Qi0FknnaEXDaT4BdrO3f1dDJAtuU  # campeonato segunda
  - 1h4CU2kyLQsjwIO8VdtpbxS7cs0a0A0BI11luqYglXxo  # campeonato tercera
  - 1r6_FwoM_6Zfp-uOEEpI5sg-IREEos8fNVe3r6WfkhyY  # detalles campeonato
