# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        language_version: python3.8
        args:
        -   --line-length=100
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
        exclude: tests/data_up_to_S2022T04
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/pycqa/flake8
    rev: '3.9.2'  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
        args: # arguments to configure flake8
        -   "--max-line-length=100"
        -   "--extend-ignore=E203"
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args:
        -   "--line-length=100"
        -   "--profile=black"
